<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-17T01:46:09</date>
  <millis>1542429969700</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-17T01:46:09</date>
  <millis>1542429969852</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Incorrect syntax near 'm'.</message>
</record>
<record>
  <date>2018-11-17T01:46:50</date>
  <millis>1542430010172</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-17T01:46:50</date>
  <millis>1542430010173</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'flaca'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-17T02:05:31</date>
  <millis>1542431131846</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-17T02:05:38</date>
  <millis>1542431138423</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'nombreMelodia'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-17T02:07:00</date>
  <millis>1542431220402</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-17T02:07:00</date>
  <millis>1542431220409</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'nombreMelodia'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-17T10:05:49</date>
  <millis>1542459949276</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-17T10:05:49</date>
  <millis>1542459949288</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name '@P0'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-17T10:08:38</date>
  <millis>1542460118201</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
</record>
<record>
  <date>2018-11-17T10:08:38</date>
  <millis>1542460118209</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>El valor no está configurado para el número de parámetro 4.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-21T17:24:10</date>
  <millis>1542831850797</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-21T17:24:11</date>
  <millis>1542831851148</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreMelodia', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-21T18:35:43</date>
  <millis>1542836143952</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-21T18:35:43</date>
  <millis>1542836143968</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreMelodia', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-21T18:37:46</date>
  <millis>1542836266686</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-21T18:37:46</date>
  <millis>1542836266686</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreMelodia', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T01:32:40</date>
  <millis>1542861160301</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
</record>
<record>
  <date>2018-11-22T01:32:40</date>
  <millis>1542861160382</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>El valor no está configurado para el número de parámetro 5.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T01:45:52</date>
  <millis>1542861952080</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
</record>
<record>
  <date>2018-11-22T01:45:52</date>
  <millis>1542861952254</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>El valor no está configurado para el número de parámetro 5.</message>
</record>
<record>
  <date>2018-11-22T01:54:45</date>
  <millis>1542862485989</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:54:46</date>
  <millis>1542862486595</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:55:11</date>
  <millis>1542862511024</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:55:11</date>
  <millis>1542862511135</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:56:14</date>
  <millis>1542862574886</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:56:14</date>
  <millis>1542862574915</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:56:44</date>
  <millis>1542862604017</millis>
  <sequence>8</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:56:44</date>
  <millis>1542862604105</millis>
  <sequence>9</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:56:50</date>
  <millis>1542862610871</millis>
  <sequence>10</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:56:50</date>
  <millis>1542862610933</millis>
  <sequence>11</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:57:13</date>
  <millis>1542862633926</millis>
  <sequence>12</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:57:13</date>
  <millis>1542862633970</millis>
  <sequence>13</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T01:57:30</date>
  <millis>1542862650952</millis>
  <sequence>14</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T01:57:31</date>
  <millis>1542862651000</millis>
  <sequence>15</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:03:15</date>
  <millis>1542862995313</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:03:15</date>
  <millis>1542862995613</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'instrumento', table 'A_Note.dbo.melodias'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-11-22T02:05:43</date>
  <millis>1542863143831</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
</record>
<record>
  <date>2018-11-22T02:05:43</date>
  <millis>1542863143858</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>El valor no está configurado para el número de parámetro 5.</message>
</record>
<record>
  <date>2018-11-22T02:07:25</date>
  <millis>1542863245608</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:07:27</date>
  <millis>1542863247394</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of PRIMARY KEY constraint 'PK__melodias__E8AF660C161503ED'. Cannot insert duplicate key in object 'dbo.melodias'. The duplicate key value is (loco).</message>
</record>
<record>
  <date>2018-11-22T02:10:56</date>
  <millis>1542863456692</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:10:56</date>
  <millis>1542863456736</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of PRIMARY KEY constraint 'PK__melodias__E8AF660C161503ED'. Cannot insert duplicate key in object 'dbo.melodias'. The duplicate key value is (loco).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:24:07</date>
  <millis>1542864247501</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:24:07</date>
  <millis>1542864247893</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Incorrect syntax near the keyword 'WHERE'.</message>
</record>
<record>
  <date>2018-11-22T02:30:25</date>
  <millis>1542864625370</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:30:26</date>
  <millis>1542864626076</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Incorrect syntax near the keyword 'WHERE'.</message>
</record>
<record>
  <date>2018-11-22T02:32:03</date>
  <millis>1542864723515</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:32:03</date>
  <millis>1542864723557</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of PRIMARY KEY constraint 'PK__melodias__E8AF660C161503ED'. Cannot insert duplicate key in object 'dbo.melodias'. The duplicate key value is (pepe).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:39:17</date>
  <millis>1542865157002</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:39:17</date>
  <millis>1542865157008</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Incorrect syntax near the keyword 'WHERE'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:47:50</date>
  <millis>1542865670666</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:47:50</date>
  <millis>1542865670949</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Incorrect syntax near ')'.</message>
</record>
<record>
  <date>2018-11-22T02:50:20</date>
  <millis>1542865820545</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:50:20</date>
  <millis>1542865820609</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of PRIMARY KEY constraint 'PK__melodias__E8AF660C161503ED'. Cannot insert duplicate key in object 'dbo.melodias'. The duplicate key value is (pepe).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:52:40</date>
  <millis>1542865960175</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-11-22T02:52:40</date>
  <millis>1542865960184</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of PRIMARY KEY constraint 'PK__melodias__E8AF660C161503ED'. Cannot insert duplicate key in object 'dbo.melodias'. The duplicate key value is (pepe).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T02:56:27</date>
  <millis>1542866187525</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:56:27</date>
  <millis>1542866187533</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
<record>
  <date>2018-11-22T02:58:15</date>
  <millis>1542866295477</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T02:58:15</date>
  <millis>1542866295478</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T03:16:18</date>
  <millis>1542867378268</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
</record>
<record>
  <date>2018-11-22T03:16:18</date>
  <millis>1542867378276</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>El valor no está configurado para el número de parámetro 4.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T19:45:24</date>
  <millis>1542926724908</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:45:24</date>
  <millis>1542926724962</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T19:46:35</date>
  <millis>1542926795021</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:46:35</date>
  <millis>1542926795023</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T19:52:13</date>
  <millis>1542927133627</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:52:15</date>
  <millis>1542927135742</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T19:53:30</date>
  <millis>1542927210069</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:53:30</date>
  <millis>1542927210104</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T19:54:24</date>
  <millis>1542927264741</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:54:24</date>
  <millis>1542927264804</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T19:54:42</date>
  <millis>1542927282920</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:54:42</date>
  <millis>1542927282976</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T19:59:10</date>
  <millis>1542927550980</millis>
  <sequence>8</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T19:59:11</date>
  <millis>1542927551036</millis>
  <sequence>9</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<record>
  <date>2018-11-22T20:00:14</date>
  <millis>1542927614657</millis>
  <sequence>10</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T20:00:14</date>
  <millis>1542927614727</millis>
  <sequence>11</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid column name 'Pega_la_vuelta'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-22T22:22:46</date>
  <millis>1542936166804</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T22:22:46</date>
  <millis>1542936166856</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
<record>
  <date>2018-11-22T22:23:19</date>
  <millis>1542936199506</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T22:23:19</date>
  <millis>1542936199506</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
<record>
  <date>2018-11-22T22:50:54</date>
  <millis>1542937854291</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T22:50:54</date>
  <millis>1542937854291</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
<record>
  <date>2018-11-22T22:51:22</date>
  <millis>1542937882591</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0001</message>
</record>
<record>
  <date>2018-11-22T22:51:22</date>
  <millis>1542937882591</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression.</message>
</record>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-02T19:40:52</date>
  <millis>1543790452755</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0002</message>
</record>
<record>
  <date>2018-12-02T19:40:52</date>
  <millis>1543790452835</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid object name 'melodias'.</message>
</record>
<record>
  <date>2018-12-02T19:41:08</date>
  <millis>1543790468893</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>S0002</message>
</record>
<record>
  <date>2018-12-02T19:41:08</date>
  <millis>1543790468894</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Invalid object name 'melodias'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-02T21:31:28</date>
  <millis>1543797088077</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-02T21:31:28</date>
  <millis>1543797088113</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-02T21:31:59</date>
  <millis>1543797119541</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-02T21:31:59</date>
  <millis>1543797119541</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-02T22:19:50</date>
  <millis>1543799990578</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-02T22:19:50</date>
  <millis>1543799990717</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-02T22:23:37</date>
  <millis>1543800217013</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-02T22:23:37</date>
  <millis>1543800217034</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:23:42</date>
  <millis>1543811022740</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:23:42</date>
  <millis>1543811022755</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:46:34</date>
  <millis>1543812394185</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:46:34</date>
  <millis>1543812394216</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:47:06</date>
  <millis>1543812426044</millis>
  <sequence>8</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:47:06</date>
  <millis>1543812426080</millis>
  <sequence>9</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:47:20</date>
  <millis>1543812440871</millis>
  <sequence>10</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:47:20</date>
  <millis>1543812440897</millis>
  <sequence>11</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:48:24</date>
  <millis>1543812504951</millis>
  <sequence>12</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:48:24</date>
  <millis>1543812504981</millis>
  <sequence>13</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:49:47</date>
  <millis>1543812587496</millis>
  <sequence>14</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:49:47</date>
  <millis>1543812587527</millis>
  <sequence>15</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:53:17</date>
  <millis>1543812797663</millis>
  <sequence>16</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:53:17</date>
  <millis>1543812797695</millis>
  <sequence>17</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:53:55</date>
  <millis>1543812835044</millis>
  <sequence>18</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:53:55</date>
  <millis>1543812835102</millis>
  <sequence>19</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:54:07</date>
  <millis>1543812847952</millis>
  <sequence>20</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:54:07</date>
  <millis>1543812847980</millis>
  <sequence>21</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T01:55:37</date>
  <millis>1543812937262</millis>
  <sequence>22</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T01:55:37</date>
  <millis>1543812937295</millis>
  <sequence>23</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__pistas__607251E5". The conflict occurred in database "A_Note", table "dbo.canciones".</message>
</record>
<record>
  <date>2018-12-03T02:13:26</date>
  <millis>1543814006652</millis>
  <sequence>24</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:13:26</date>
  <millis>1543814006681</millis>
  <sequence>25</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreCancion', table 'A_Note.dbo.notas'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-12-03T02:13:58</date>
  <millis>1543814038949</millis>
  <sequence>26</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:13:58</date>
  <millis>1543814038965</millis>
  <sequence>27</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T02:13:59</date>
  <millis>1543814039894</millis>
  <sequence>28</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:13:59</date>
  <millis>1543814039910</millis>
  <sequence>29</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreCancion', table 'A_Note.dbo.notas'; column does not allow nulls. INSERT fails.</message>
</record>
</log>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-03T02:28:10</date>
  <millis>1543814890462</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:28:10</date>
  <millis>1543814890637</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Cannot insert the value NULL into column 'nombreCancion', table 'A_Note.dbo.notas'; column does not allow nulls. INSERT fails.</message>
</record>
<record>
  <date>2018-12-03T02:29:17</date>
  <millis>1543814957713</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:29:17</date>
  <millis>1543814957741</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T02:29:31</date>
  <millis>1543814971413</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:29:31</date>
  <millis>1543814971437</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T02:30:27</date>
  <millis>1543815027446</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:30:27</date>
  <millis>1543815027476</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-03T02:44:52</date>
  <millis>1543815892934</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:44:53</date>
  <millis>1543815893097</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T02:47:49</date>
  <millis>1543816069313</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T02:47:49</date>
  <millis>1543816069339</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-12-03T03:13:52</date>
  <millis>1543817632910</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T03:13:52</date>
  <millis>1543817632918</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T03:13:52</date>
  <millis>1543817632928</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T03:13:52</date>
  <millis>1543817632929</millis>
  <sequence>3</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__notas__PistaID__671F4F74". The conflict occurred in database "A_Note", table "dbo.pistas", column 'PistaID'.</message>
</record>
<record>
  <date>2018-12-03T03:15:39</date>
  <millis>1543817739648</millis>
  <sequence>4</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T03:15:39</date>
  <millis>1543817739649</millis>
  <sequence>5</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>Violation of UNIQUE KEY constraint 'UQ__pistas__E56EF00FBB9EACEC'. Cannot insert duplicate key in object 'dbo.pistas'. The duplicate key value is (verso).</message>
</record>
<record>
  <date>2018-12-03T03:15:39</date>
  <millis>1543817739654</millis>
  <sequence>6</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>23000</message>
</record>
<record>
  <date>2018-12-03T03:15:39</date>
  <millis>1543817739654</millis>
  <sequence>7</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>utils.database.logger.FileLogger</class>
  <method>logSevere</method>
  <thread>1</thread>
  <message>The INSERT statement conflicted with the FOREIGN KEY constraint "FK__notas__PistaID__671F4F74". The conflict occurred in database "A_Note", table "dbo.pistas", column 'PistaID'.</message>
</record>
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
